<a href="https://colab.research.google.com/github/Prajwalsk45/Machine-Learning/blob/main/classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([0,1,1,1])

In [ ]:

y

array([0, 1, 1, 1])

In [ ]:
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [ ]:
weight=np.array([1,1]) #precomputed weights
weight

array([1, 1])

In [ ]:
bais=-0.5

In [ ]:
def activation(z):
  if z>0:
    return 1
  else:
    return 0


pred=[]
for a in x:
  y_hat=np.dot(a,weight)+b
  pred.append(activation(y_hat))


In [ ]:
pred

[0, 1, 1, 1]

In above example we assigned default weight(preconfiguredd values)

Now we change weight value for each epoch

In [ ]:
import math


In [ ]:
epochs=100
alpha=0.2

In [ ]:
weight0=np.random.random()  #random weight values
weight1=np.random.random()
weight2=np.random.random()
print(weight0)
print(weight1)
print(weight2)


0.4293104819252699
0.0960200731062385
0.5432712527313953


In [ ]:
#partial derivative
del_weight0=1
del_weight1=1
del_weight2=1


In [ ]:
#three input(or gate)
train_data=np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
op=np.array([0,1,1,1,1,1,1,1])

In [ ]:
bias=0
for i in range(epochs):
  for x in tarin_data:
    y_hat=weight0*x[0]+weight1*x[1]+weight2*x[2]+bias

    if(r)
